=== Windy-Secker/WSPVI-alpha/xml/ini.dtd
<!DOCTYPE ini[
<!ELEMENT ini (font,maincolor)>
<!ELEMENT font (handwriting1,handwriting2,artwriting1,artwriting2,printing1,printing2)>
<!ELEMENT handwriting1 (#PCDATA)>
<!ELEMENT handwriting2 (#PCDATA)>
<!ELEMENT artwriting1 (#PCDATA)>
<!ELEMENT ariwriting2 (#PCDATA)>
<!ELEMENT printing1 (#PCDATA)>
<!ELEMENT printing2 (#PCDATA)>
<!ELEMENT maincolor (green,red,blue,night,white,yellow)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT blue (#PCDATA)>
<!ELEMENT night (#PCDATA)>
<!ELEMENT white (#PCDATA)>
<!ELEMENT yellow (#PCDATA)>
]>

=== Windy-Secker/WSPVI-alpha/xml/ini.xml
<?xml version="1.0.0" encoding="utf-8">
<!DOCTYPE ini SYSTEM "ini.dtd">
<ini>
  <font>
    <handwriting1>h1.ttf</handwriting1>
    <handwriting2>h2.ttf</handwriting2>
    <artwriting1>a1.ttf</artwriting1>
    <artwriting2>a2.ttf</artwriting2>
    <printing1>p1.ttf</printing1>
    <printing2>p2.ttf</printing2>
  </font>
  <maincolor>
    <green>green.css</green>
    <red>red.css</red>
    <blue>blue.css</blue>
    <night>night.css</night>
    <snow>snow.css</snow>
    <yellow>yellow.css</yellow>
  </maincolor>
<ini>
